In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
data = pd.read_json('/Users/semyonemakov/VK_Parser/people_close.json')
data.head()

   NUMBER      ID                     LINK  CITY  AGE
0       1   53046   https://vk.com/id53046   NaN  NaN
1       2   53182   https://vk.com/id53182   NaN  NaN
2       3   57894   https://vk.com/id57894   NaN  NaN
3       4   63253   https://vk.com/id63253   NaN  NaN
4       5  148924  https://vk.com/id148924   NaN  NaN

In [5]:
fc_groups = pd.read_json('/Users/semyonemakov/VK_Parser/football_groups.json')

In [7]:
fc_groups

,ID,LINK,NAME,theme
0,52513455,https://vk.com/public52513455,FC LongRun Community,Спортивный клуб
1,75099129,https://vk.com/public75099129,Fantasy Premier League,Футбол
2,39911616,https://vk.com/public39911616,Omar Momani,Футбол
3,34732382,https://vk.com/public34732382,Евро футбол плюс | Все о футболе!,Футбол
4,220367997,https://vk.com/public220367997,Лига будней FL,Спортивная организация
...,...,...,...,...
80,34459228,https://vk.com/public34459228,Смотри ЕВРО 2024,Футбол
81,202493653,https://vk.com/public202493653,FONBET Кубок России,Спортивная организация
82,145829492,https://vk.com/public145829492,ФК «Казанка» Москва,Футбольная команда
83,35027856,https://vk.com/public35027856,Футбольные обзоры | Новости футбола - спорт,Футбол
84,30651595,https://vk.com/public30651595,ФК «Локомотив»,Футбольная команда